# Generated by Django 2.1.4 on 2018-12-26 12:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181226_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 26, 12, 15, 7, 76654, tzinfo=utc)),
        ),
    ]
